services:
- type: pserv
  repo: https://github.com/nakshat-ra/render
  rootDir: .
  name: agent-example
  runtime: docker       
  plan: starter
  envVars:
  - fromGroup: agent-example-env 
  region: virginia
  maxShutdownDelaySeconds: 300
  scaling:
    minInstances: 1
    maxInstances: 4
    targetCPUPercent: 60
    targetMemoryPercent: 60
version: "1"
