services:
- type: web
  repo: https://github.com/nakshat-ra/render
  rootDir: .
  name: agent-example
  runtime: docker       
  plan: free
  envVars:
  - fromGroup: agent-example-env-group
  region: virginia
  # maxShutdownDelaySeconds: 300
  # scaling:
  #   minInstances: 1
  #   maxInstances: 4
  #   targetCPUPercent: 60
  #   targetMemoryPercent: 60
version: "1"
